name: hiv_drm_enricher
channels:
  - conda-forge # Add if not present, needs higher priority for dorado
  - bioconda
  - defaults
dependencies:
  # Core Python version
  - python=3.10

  # Key bioinformatics libraries
  - pysam
  - mappy
  - samtools

  # For building the database
  - requests
  - pandas
  - lxml
  - html5lib
  - selenium
  - webdriver-manager

  # --- NEW TOOLS ---
  - dorado   # Nanopore basecaller
  - minimap2 # Aligner

  # Optional but good for development
  - ipython
  - black